### ISSUE TITLE
添加新主干网络的疑问

### ISSUE THREAD

**Issue by buildcharger** [PaddlePaddle/PALM#26]
请问是否可以自主组织网络结构？
假如可以，能否提供组织gpt（open ai）网络的思路？

**Comment by xyzhou-puck** [comment]
@xixiaoyao , please answer this question.

**Comment by xixiaoyao** [comment]
我们即将发布的版本会支持网络结构自定义的哈，未来也会考虑将自回归语言模型进行内置

**Comment by xixiaoyao** [comment]
组件（包括主干网络）的自定义教程已添加，请参考 [《组件定制化教程》](https://github.com/PaddlePaddle/PALM/blob/master/customization_cn.md) 进行操作，感谢您对PALM的关注。
