### ISSUE TITLE
函数引用出错

### ISSUE THREAD

**Issue by siyideng163** [PaddlePaddle/PALM#45]
paddle.fluid.layers中并没有switch_case函数，在paddle的官网API指南中也没有找到相关函数。

File "/media/dsy/PALM-master/paddlepalm/mtl_controller.py", line 502, in _init_train
    loss = layers.switch_case(
AttributeError: module 'paddle.fluid.layers' has no attribute 'switch_case'

**Comment by xyzhou-puck** [comment]
@xixiaoyao ，please look at this issue

**Comment by xixiaoyao** [comment]
你好，master分支使用的switch_case是paddle即将发版的v1.7里面的，可以先安装v0.2.3版本的试用哦

**Comment by siyideng163** [comment]
@xixiaoyao 您好，可是PaddlePaddle-gpu安装版本里面没有您说的v0.2.3，以下是显示可选的安装版本
(from versions: 1.0.0.post85, 1.0.0.post87, 1.0.0.post97, 1.0.1.post85, 1.0.1.post87, 1.0.1.post97, 1.0.2.post85, 1.0.2.post87, 1.0.2.post97, 1.1.0.post85, 1.1.0.post87, 1.1.0.post97, 1.2.0.post85, 1.2.0.post87, 1.2.0.post97, 1.2.1.post85, 1.2.1.post87, 1.2.1.post97, 1.3.0.post85, 1.3.0.post87, 1.3.0.post97, 1.3.1.post85, 1.3.1.post87, 1.3.1.post97, 1.3.2.post85, 1.3.2.post87, 1.3.2.post97, 1.4.0.post85, 1.4.0.post87, 1.4.0.post97, 1.4.1.post85, 1.4.1.post87, 1.4.1.post97, 1.5.0.post87, 1.5.0.post97, 1.5.0.post107, 1.5.1.post87, 1.5.1.post97, 1.5.1.post107, 1.5.2.post87, 1.5.2.post97, 1.5.2.post107, 1.6.0rc0.post107, 1.6.0.post97, 1.6.0.post107, 1.6.1.post97, 1.6.1.post107, 1.6.2.post97, 1.6.2.post107)

**Comment by xixiaoyao** [comment]
PALM所依赖的Paddle V1.7版本已发布，现已可以通过pip直接安装
```
pip install paddlepalm
```
感谢您对PALM的关注。
