### ISSUE TITLE
paddle 版本

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/PALM#54]
现在已发布的paddle版本最高为1.6
而PALM要求1.7

**Comment by xyzhou-puck** [comment]
感谢对PALM的关注，我们在紧锣密鼓地筹备1.7的发布，很快就要跟大家见面了，如果需要历史版本的话，我们可以把旧版本放到特定分支里。

**Comment by Mryangkaitong** [comment]
> 
> 
> 感谢对PALM的关注，我们在紧锣密鼓地筹备1.7的发布，很快就要跟大家见面了，如果需要历史版本的话，我们可以把旧版本放到特定分支里。

嗯嗯，放一下吧，谢谢

**Comment by xixiaoyao** [comment]
感谢关注，历史版本已打tag，可以在这里找到

![image](https://user-images.githubusercontent.com/24541791/74301224-62b55580-4d8d-11ea-9be6-b02e26de9354.png)

支持1.6版本paddle的是v0.2.X的PALM，但是我们更建议使用最新版的PALM，您可以先从 [这里](https://www.paddlepaddle.org.cn/install/doc/tables)`多版本whl包列表-dev
`一节中 下载dev版本的paddle（基本等同于即将发版的paddle v1.7），然后最新版的PALM就可以使用了（从源码安装哦，最新版暂未上传pip源）。

**Comment by Mryangkaitong** [comment]
> 
> 
> 感谢关注，历史版本已打tag，可以在这里找到
> 
> ![image](https://user-images.githubusercontent.com/24541791/74301224-62b55580-4d8d-11ea-9be6-b02e26de9354.png)
> 
> 支持1.6版本paddle的是v0.2.X的PALM，但是我们更建议使用最新版的PALM，您可以先从 [这里](https://www.paddlepaddle.org.cn/install/doc/tables)`多版本whl包列表-dev `一节中 下载dev版本的paddle（基本等同于即将发版的paddle v1.7），然后最新版的PALM就可以使用了（从源码安装哦，最新版暂未上传pip源）。

好的谢谢

**Comment by Mryangkaitong** [comment]
> 
> 
> 感谢关注，历史版本已打tag，可以在这里找到
> 
> ![image](https://user-images.githubusercontent.com/24541791/74301224-62b55580-4d8d-11ea-9be6-b02e26de9354.png)
> 
> 支持1.6版本paddle的是v0.2.X的PALM，但是我们更建议使用最新版的PALM，您可以先从 [这里](https://www.paddlepaddle.org.cn/install/doc/tables)`多版本whl包列表-dev `一节中 下载dev版本的paddle（基本等同于即将发版的paddle v1.7），然后最新版的PALM就可以使用了（从源码安装哦，最新版暂未上传pip源）。

多版本whl包列表-dev 下载的是-版本是0.0.0？安装最新的PALM还是会报错

**Comment by xixiaoyao** [comment]
Paddle 1.7版本已发布，现已支持直接安装。
```
pip install paddlepalm
```
感谢您对PALM的关注。
