### ISSUE TITLE
在jupyter notebook 运行报错?

### ISSUE THREAD

**Issue by binwang672012** [PaddlePaddle/PALM#68]
如图,在jupyter notebook 下运行报错,经过重装paddle,重启jupyter ,重启系统的情况下仍然如此,不知道为何,希望能帮忙查找下原因,感谢.

![Selection_057](https://user-images.githubusercontent.com/53250648/76502042-4c7ae200-647e-11ea-86e5-4f801ba706f4.jpg)

具体报错信息如下:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8e77d7a7bdb7> in <module>
----> 1 import paddlepalm

~/anaconda3/lib/python3.7/site-packages/paddlepalm/__init__.py in <module>
      5 from . import lr_sched
      6 from . import backbone
----> 7 from . import reader
      8 from . import head
      9 

~/anaconda3/lib/python3.7/site-packages/paddlepalm/reader/__init__.py in <module>
      1 
----> 2 from .cls import ClassifyReader
      3 from .match import MatchReader
      4 from .seq_label import SequenceLabelReader
      5 from .mrc import MRCReader

~/anaconda3/lib/python3.7/site-packages/paddlepalm/reader/cls.py in <module>
     15 
     16 from paddlepalm.reader.base_reader import Reader
---> 17 from paddlepalm.reader.utils.reader4ernie import ClassifyReader as CLSReader
     18 
     19 

~/anaconda3/lib/python3.7/site-packages/paddlepalm/reader/utils/reader4ernie.py in <module>
     40 if six.PY3:
     41     import io
---> 42     sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
     43     sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
     44 

AttributeError: 'OutStream' object has no attribute 'buffer'`

**Comment by GitLD** [comment]
好像只是在jupyter不行，直接在python中执行是没有问题的，我也遇到了一样的问题

**Comment by xixiaoyao** [comment]
感谢对PALM的关注，已fix，可以pull一下最新版的代码再试一下

**Comment by binwang672012** [comment]
> 感谢对PALM的关注，已fix，可以pull一下最新版的代码再试一下

OK了,非常感谢您!
