### ISSUE TITLE
运行classification example报错？

### ISSUE THREAD

**Issue by GitLD** [PaddlePaddle/PALM#71]
# AIStudio环境
Py3.7+Paddle1.7.0
基于git安装palm

# 运行错误
运行example情感分类预测阶段报错
![error](https://user-images.githubusercontent.com/30947306/76820577-8cf3aa80-6846-11ea-9315-61da73bdc9f7.PNG)

**Comment by xixiaoyao** [comment]
感谢对PALM的关注，该问题已fix，麻烦pull一下最新版的代码再试一下
