### ISSUE TITLE
paddlepalm安装中报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PALM#73]
环境：aistudio 高端版 python3.7  PaddlePaddle 1.7.1

在命令行里安装之后测试正常，在notebook里面测试就报错。
在notebook里面运行：from paddlepalm import downloader

---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-6-4be91a4acd9e> in <module>
----> 1 from paddlepalm import downloader
      2 downloader.ls('pretrain')
~/extlib/paddlepalm/__init__.py in <module>
      5 from . import lr_sched
      6 from . import backbone
----> 7 from . import reader
      8 from . import head
      9 
~/extlib/paddlepalm/reader/__init__.py in <module>
      1 
----> 2 from .cls import ClassifyReader
      3 from .match import MatchReader
      4 from .seq_label import SequenceLabelReader
      5 from .mrc import MRCReader
~/extlib/paddlepalm/reader/cls.py in <module>
     15 
     16 from paddlepalm.reader.base_reader import Reader
---> 17 from paddlepalm.reader.utils.reader4ernie import ClassifyReader as CLSReader
     18 
     19 
~/extlib/paddlepalm/reader/utils/reader4ernie.py in <module>
     40 if six.PY3:
     41     import io
---> 42     sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
     43     sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
     44 
AttributeError: 'OutStream' object has no attribute 'buffer'

**Comment by xixiaoyao** [comment]
你好，该问题已修复，请尝试安装最新版的PALM（版本>=2.0.1），感谢您对PALM的关注。
