### ISSUE TITLE
请问如何用PALM对Ernie进行预训练？

### ISSUE THREAD

**Issue by 131250208** [PaddlePaddle/PALM#74]
在例子中只看到load_pretrain，没看到用自己的语料进行预训练的过程，请问可以举例说明一下吗？

**Comment by xixiaoyao** [comment]
如果是想按照自己的settings进行预训练，可以在创建backbone时直接用构造函数创建（不从`from_config`创建），当然也可以`from_config`。然后不用调用`load_pretrain`函数，直接创建Mask Language Model用自己的语料预训练即可，框架会自动完成参数的随机初始化
